#!/usr/bin/expect

spawn telnet 192.168.56.101 5082
send "\r"
expect "#"
send "conf t\r"
expect "(config)#"
send "hostname C1\r"
expect "(config)#"
send "int eth1/0\r"
expect "(config-if)#"
send "ip add dhcp\r"
expect "(config-if)#"
send "ip nat outside\r"
expect "(config-if)#"
send "no shut\r"
send "exit\r"
expect "(config)#"
send "\r"
send "int eth1/0\r"
expect "(config-subif)#"
send "encapsulation dot1q 10\r"
expect "(config-subif)#"
send "ip add 10.5.10.254 255.255.255.0\r"
expect "(config-subif)#"
send "ip nat inside\r"
expect "(config-subif)#"
send "no shut\r"
expect "(config-subif)#"
send "exit\r"
send "\r"
expect "(config)#"
send "int eth1/0.20\r"
expect "(config-subif)#"
send "encapsulation dot1q 20\r"
expect "(config-subif)#"
send "ip add 10.5.20.254 255.255.255.0\r"
expect "(config-subif)#"
send "ip nat inside\r"
expect "(config-subif)#"
send "no shut\r"
expect "(config-subif)#"
send "exit\r"
send "\r"
expect "(config)#"
send "int eth1/0.30\r"
expect "(config-subif)#"
send "encapsulation dot1q 30\r"
expect "(config-subif)#"
send "ip add 10.5.30.254 255.255.255.0\r"
expect "(config-subif)#"
send "ip nat inside\r"
expect "(config-subif)#"
send "no shut\r"
expect "(config-subif)#"
send "exit\r"
send "\r"
expect "(config)#"
send "int eth1/1\r"
expect "(config-if)#"
send "no shut\r"
send "exit\r"
expect "(config)#"
send "ip nat inside source list 1 interface Ethernet 1/0\r"
expect "(config)#"
send "access-list 1 permit 10.0.0.0 0.255.255.255\r"
send "exit\r"
expect "C1#"
send "wr\r"
send "\r"
expect "#"
send "\x1D"
expect "telnet>"
send "quit\r"