#!/usr/bin/expect

spawn telnet 192.168.56.101 5083
send "\r"
expect "#"
send "conf t\r"
expect "(config)#"
send "hostname D1\r"
expect "(config)#"
send "vlan 10\r"
expect "(config-vlan)#"
send "name Utilisateurs\r"
send "exit\r"
expect "(config)#"
send "vlan 20\r"
expect "(config-vlan)#"
send "name Stagiaire\r"
send "exit\r"
expect "(config)#"
send "vlan 30\r"
expect "(config-vlan)#"
send "name Imprimantes\r"
send "exit\r"
expect "(config)#"
send "vlan 40\r"
expect "(config-vlan)#"
send "name Administrateurs\r"
send "exit\r"
expect "(config)#"
send "vlan 50\r"
expect "(config-vlan)#"
send "name Serveurs\r"
send "exit\r"
expect "(config)#"
send "vlan 60\r"
expect "(config-vlan)#"
send "name Serveurs-Sensibles\r"
send "exit\r"
send "exit\r"
expect "#"
send "wr\r"
send "\r"
expect "#"
send "\x1D"
expect "telnet>"
send "quit\r"

set i 0
set ip_serv 192.168.56.101
set list_port [list 5084 5085 5086 5087 5088]
foreach port $list_port {
    set i [expr {$i + 1}]
    spawn telnet $ip_serv $port
    send "\r"
    expect "#"
    send "conf t\r"
    expect "(config)#"
    send "hostname SW$i\r"
    expect "(config)#"
    send "vlan 10\r"
    expect "(config-vlan)#"
    send "name Utilisateurs\r"
    send "exit\r"
    expect "(config)#"
    send "vlan 20\r"
    expect "(config-vlan)#"
    send "name Stagiaire\r"
    send "exit\r"
    expect "(config)#"
    send "vlan 30\r"
    expect "(config-vlan)#"
    send "name Imprimantes\r"
    send "exit\r"
    expect "(config)#"
    send "vlan 40\r"
    expect "(config-vlan)#"
    send "name Administrateurs\r"
    send "exit\r"
    expect "(config)#"
    send "vlan 50\r"
    expect "(config-vlan)#"
    send "name Serveurs\r"
    send "exit\r"
    expect "(config)#"
    send "vlan 60\r"
    expect "(config-vlan)#"
    send "name Serveurs-Sensibles\r"
    send "exit\r"
    send "exit\r"
    expect "#"
    send "wr\r"
    send "\r"
    expect "#"
    send "\x1D"
    expect "telnet>"
    send "quit\r"
}